import { execSync } from "node:child_process";
import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";
import { encryptSecret, generateTOTPSecret } from "../utils/totp";

/**
 * Global setup for integration tests.
 *
 * Required env vars (the test runner exits with a clear message if missing):
 *   - TEST_DATABASE_URL: a Postgres URL the test user can drop + recreate
 *
 * What this does once per `npm run test:integration`:
 *   1. Sets DATABASE_URL = TEST_DATABASE_URL so Prisma + the API see the
 *      test database.
 *   2. Runs `prisma db push --force-reset --skip-generate` to drop & recreate
 *      the schema fresh. Faster than migrate reset since we don't need
 *      migration history in tests.
 *   3. Seeds the baseline rows every test relies on:
 *        - One domain in the whitelist: example.com
 *        - Three business units: BU-A (active), BU-B (active), BU-C (inactive)
 *        - One account: ACME
 *        - A canonical TOTP secret all test users share, plus the shared
 *          password — both exported via helpers so tests can authenticate.
 *
 * Returns a teardown function that closes the Prisma connection so vitest
 * exits cleanly.
 */

const TEST_DB_ENV = "TEST_DATABASE_URL";

export const TEST_PASSWORD = "test-password-12345";
export const TEST_DOMAIN = "example.com";

// Per-test-run TOTP secret — every seeded user gets this same encrypted
// secret. Tests generate codes from the plaintext via the helpers module.
export const TEST_TOTP_SECRET = "JBSWY3DPEHPK3PXP";

export default async function globalSetup() {
  const url = process.env[TEST_DB_ENV];
  if (!url) {
    throw new Error(
      `\n\n❌ Integration tests require ${TEST_DB_ENV} to be set.\n\n` +
        `Example for a local Postgres:\n` +
        `  ${TEST_DB_ENV}=postgresql://quanta_test:test@localhost:5432/quanta_test \\\n` +
        `    npm run test:integration\n\n` +
        `The test user must have permission to drop and recreate the public schema.\n`
    );
  }

  // Make sure both Prisma CLI and the app code see the test database.
  process.env.DATABASE_URL = url;

  // ── 1. Reset schema via prisma db push ──
  // --force-reset drops and recreates without prompting; --skip-generate
  // avoids regenerating the client (it was already generated by postinstall).
  // --accept-data-loss is required after --force-reset on some Prisma
  // versions; we include it for forwards compatibility.
  try {
    execSync(
      `npx prisma db push --force-reset --skip-generate --accept-data-loss`,
      {
        env: { ...process.env, DATABASE_URL: url },
        stdio: ["ignore", "ignore", "inherit"],
      }
    );
  } catch (err) {
    throw new Error(
      `\n\n❌ Failed to push schema to test database.\n` +
        `Check that ${TEST_DB_ENV} points to a Postgres reachable by Prisma,\n` +
        `and that the configured user can drop the public schema.\n\n` +
        `Underlying error: ${(err as Error).message}\n`
    );
  }

  // ── 2. Baseline seed ──
  const prisma = new PrismaClient();
  try {
    // Domain whitelist — one entry so registration tests have a known good
    // domain plus a known bad domain (any other suffix).
    // The first test user owns this row; we'll seed that user below.
    const passwordHash = await bcrypt.hash(TEST_PASSWORD, 6); // lower cost in tests
    const encryptedTOTP = encryptSecret(TEST_TOTP_SECRET);

    // Bootstrap admin so we have an AA to seed the rest under.
    // (DomainWhitelist requires addedBy → User → primaryBu → BU, so order
    // matters: BU → AA user → domain.)
    const buA = await prisma.businessUnit.create({
      data: { code: "BU-A", name: "Alpha Studio", isActive: true },
    });
    const buB = await prisma.businessUnit.create({
      data: { code: "BU-B", name: "Beta Studio", isActive: true },
    });
    await prisma.businessUnit.create({
      data: { code: "BU-C", name: "Gamma Studio (deactivated)", isActive: false },
    });

    const aa = await prisma.user.create({
      data: {
        email: `aa@${TEST_DOMAIN}`,
        name: "Aria Admin",
        passwordHash,
        roles: ["AA"],
        primaryBuId: buA.id,
        totpSecret: encryptedTOTP,
        totpVerified: true,
        isActive: true,
      },
    });

    await prisma.domainWhitelist.create({
      data: { domain: TEST_DOMAIN, addedBy: aa.id },
    });

    await prisma.account.create({
      data: {
        name: "ACME Corp",
        code: "ACME",
        isActive: true,
      },
    });
  } finally {
    await prisma.$disconnect();
  }

  // ── 3. Teardown — close Prisma when vitest finishes ──
  return async () => {
    const prisma = new PrismaClient();
    await prisma.$disconnect();
  };
}

// Sanity: ensure the TOTP helpers haven't been swapped under us when this
// file is imported indirectly. The Buffer of TEST_TOTP_SECRET is 16 bytes;
// the encryptSecret round-trip must produce a non-empty ciphertext.
void generateTOTPSecret; // silence unused import if helpers change later
